---
name: actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/*.ya?ml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.actor != 'renovate[bot]' }}
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Run actionlint with reviewdog
        timeout-minutes: 5
        uses: reviewdog/action-actionlint@v1.37.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
