---
name: terraform-docs

on:
  pull_request:

jobs:
  dirs:
    runs-on: ubuntu-latest
    outputs:
      target_dirs: ${{ steps.uniq_dirs.outputs.d }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6
        with:
          PATTERNS: |
            aws/**
            datadog/**

      - name: uniq dirs
        id: uniq_dirs
        run: |
          d=$(echo ${{ env.GIT_DIFF }} | xargs dirname | sort | uniq | jq -cnR '[inputs | select(length > 0)]')
          echo "d=$d" >> "$GITHUB_OUTPUT"

  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    if: needs.dirs.outputs.target_dirs != '[]' && needs.dirs.outputs.target_dirs != ''
    needs: [dirs]
    strategy:
      fail-fast: false
      matrix:
        target_dir: ${{ fromJson(needs.dirs.outputs.target_dirs) }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: aquaproj/aqua-installer@928a2ee4243a9ee8312d80dc8cbaca88fb602a91 # v2.2.0
        with:
          aqua_version: v2.23.0

      - name: Render terraform docs and push changes back to PR
        run: terraform-docs markdown ${{ matrix.target_dir }} --output-file README.md

      - run: |
          if [ "$(git status -s)" != "" ]; then
            git --no-pager diff
            exit 1
          fi
