---
name: terraform-docs

on:
  pull_request:

env:
  HEAD_REF: ${{ github.head_ref }}

jobs:
  dirs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: uniq dirs
        id: uniq_dirs
        run: |
          d=$(git diff --diff-filter=AMRCD \
                --name-only \
                "${{ env.HEAD_REF }}..origin/main" \
                "**.tf" \
                | xargs dirname \
                | sort -u \
                | grep -v examples \
                | jq -cnR '[inputs | select(length > 0)]' \
                || true
              )
          echo "d=$d" >> "$GITHUB_OUTPUT"
    outputs:
      target_dirs: ${{ steps.uniq_dirs.outputs.d }}

  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    if: needs.dirs.outputs.target_dirs != '[]' && needs.dirs.outputs.target_dirs != ''
    needs: [dirs]
    strategy:
      fail-fast: false
      matrix:
        target_dir: ${{ fromJson(needs.dirs.outputs.target_dirs) }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: v2.23.1
      - name: Render terraform docs and push changes back to PR
        run: terraform-docs markdown ${{ matrix.target_dir }} --output-file README.md
      - run: |
          if [ "$(git status -s)" != "" ]; then
            git --no-pager diff
            exit 1
          fi
