---
name: ghalint

on: workflow_call

jobs:
  ghalint:
    # Validate GitHub Actions Workflows by ghalint.
    runs-on: ${{ vars.RUNNER_AMD }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup aqua
        timeout-minutes: 5
        uses: aquaproj/aqua-installer@fd2089d1f56724d6456f24d58605e6964deae124 # v2.3.2
        with:
          aqua_version: v2.25.0
      - name: GHALint
        run: ghalint run
        env:
          GHALINT_LOG_COLOR: always
