---
name: Run gitleaks

on: workflow_call

jobs:
  gitleaks:
    name: Run gitleaks
    runs-on: ${{ vars.RUNNER_AMD }}
    timeout-minutes: 13
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Setup aqua
        timeout-minutes: 5
        uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: v2.23.2
      - name: Run gitleaks
        timeout-minutes: 5
        run: gitleaks detect -v
