---
name: Run taplo

on: workflow_call

jobs:
  taplo:
    name: Run taplo
    runs-on: ${{ vars.RUNNER_AMD }}
    timeout-minutes: 6
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup aqua
        timeout-minutes: 5
        uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: v2.24.1
      - name: Run taplo
        timeout-minutes: 3
        run: taplo format --check
